table Penetracion-totales
	lineageTag: cc1ebe82-d9c8-4175-9622-3f26788a785f

	column Año
		dataType: int64
		formatString: 0
		lineageTag: 5e2d1be5-82f4-4dc3-949f-63d89c71596d
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: int64
		formatString: 0
		lineageTag: d218d41f-25a1-4c77-8fdd-f321d4d80079
		summarizeBy: sum
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column 'Accesos por cada 100 hogares'
		dataType: double
		lineageTag: 77f0ffd9-7768-4c8e-85c9-0c98393822ee
		summarizeBy: sum
		sourceColumn: Accesos por cada 100 hogares

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Accesos por cada 100 hab'
		dataType: double
		lineageTag: 26655d47-88a7-44c3-9ada-d07596d4cae1
		summarizeBy: sum
		sourceColumn: Accesos por cada 100 hab

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Periodo
		dataType: string
		lineageTag: e8d5cf77-8ee3-4e4b-aec5-9b4789e09424
		summarizeBy: none
		sourceColumn: Periodo

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: string
		lineageTag: 2c2c6690-352e-461e-8f0e-6b2bc495dd47
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

	column Sufijo
		dataType: string
		lineageTag: b0b4d064-0c0b-45d2-bb16-99591bf2eb87
		summarizeBy: none
		sourceColumn: Sufijo

		annotation SummarizationSetBy = Automatic

	partition Penetracion-totales = m
		mode: import
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\rubio\Documents\SoyHenry\Proyecto_Individual\Internet.xlsx"), null, true),
				    #"Penetracion-totales_Sheet" = Origen{[Item="Penetracion-totales",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(#"Penetracion-totales_Sheet", [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Año", Int64.Type}, {"Trimestre", Int64.Type}, {"Accesos por cada 100 hogares", type number}, {"Accesos por cada 100 hab", type number}, {"Periodo", type text}, {"Column6", type any}, {"Column7", type any}, {"Column8", type any}, {"Column9", type any}, {"Column10", type any}, {"Column11", type any}, {"Column12", type any}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado",{"Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12"}),
				    #"Personalizada agregada" = Table.AddColumn(#"Columnas quitadas", "Fecha", each [Año][Trimestre][Periodo]),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Personalizada agregada",{"Fecha"}),
				    #"Personalizada agregada1" = Table.AddColumn(#"Columnas quitadas1", "Personalizado", each [Año]+[Trimestre]+[Periodo]),
				    #"Columnas quitadas2" = Table.RemoveColumns(#"Personalizada agregada1",{"Personalizado"}),
				    #"Fecha analizada insertada" = Table.AddColumn(#"Columnas quitadas2", "Analizar", each Date.From(DateTimeZone.From([Periodo])), type date),
				    #"Columnas quitadas3" = Table.RemoveColumns(#"Fecha analizada insertada",{"Analizar"}),
				    #"Columna duplicada" = Table.DuplicateColumn(#"Columnas quitadas3", "Periodo", "Periodo - Copia"),
				    #"Primeros caracteres insertados" = Table.AddColumn(#"Columna duplicada", "Primeros caracteres", each Text.Start([#"Periodo - Copia"], 7), type text),
				    #"Columnas quitadas4" = Table.RemoveColumns(#"Primeros caracteres insertados",{"Periodo - Copia"}),
				    #"Columna combinada insertada" = Table.AddColumn(#"Columnas quitadas4", "Fecha", each Text.Combine({Text.From([Año], "es-419"), " ", [Primeros caracteres]}), type text),
				    #"Columnas quitadas5" = Table.RemoveColumns(#"Columna combinada insertada",{"Fecha", "Primeros caracteres"}),
				    #"Columna combinada insertada1" = Table.AddColumn(#"Columnas quitadas5", "Fecha", each Text.Combine({Text.From([Año], "es-419"), " ", Text.From([Trimestre], "es-419")}), type text),
				    #"Sufijo insertado" = Table.AddColumn(#"Columna combinada insertada1", "Sufijo", each [Fecha] & "° trim", type text)
				in
				    #"Sufijo insertado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

